export interface TutorialIndexModule {
  title: string;
  view: string;
  plan: "basic" | "pro" | "enterprise" | "admin";
  summary: string;
  idealFor: string;
  purpose: string;
  whenToUse: string;
  needs: string[];
  produces: string[];
  controls: string[];
  related: string[];
}

export interface TutorialIndexGroup {
  group: string;
  description: string;
  modules: TutorialIndexModule[];
}

const module = (
  title: string,
  view: string,
  plan: TutorialIndexModule["plan"],
  summary: string,
  idealFor: string,
  purpose: string,
  whenToUse: string,
  needs: string[],
  produces: string[],
  controls: string[],
  related: string[],
): TutorialIndexModule => ({
  title,
  view,
  plan,
  summary,
  idealFor,
  purpose,
  whenToUse,
  needs,
  produces,
  controls,
  related,
});

export const tutorialMasterIndex: TutorialIndexGroup[] = [
  {
    group: "Principal",
    description: "Vista de control diario y coordinacion de trabajo.",
    modules: [
      module(
        "Dashboard",
        "dashboard",
        "basic",
        "Centro de mando con KPIs, alertas y accesos operativos.",
        "Revision diaria de gerencia y contador.",
        "Concentrar en una sola pantalla el estado comercial, contable, fiscal y operativo de la empresa.",
        "Abrelo al inicio del dia, antes del cierre y cuando necesites priorizar incidencias.",
        ["Datos operativos ya registrados en ventas, compras, bancos, nomina e impuestos."],
        ["KPIs", "alertas priorizadas", "accesos rapidos a documentos o modulos criticos"],
        ["Alertas tributarias abiertas", "conciliaciones pendientes", "descuadres o vencimientos"],
        ["configuracion", "facturacion", "bancos", "declaraciones-tributarias", "nomina"],
      ),
    ],
  },
  {
    group: "Contabilidad",
    description: "Nucleo del registro, control y analisis financiero.",
    modules: [
      module(
        "Plan de Cuentas",
        "plan-cuentas",
        "basic",
        "Catalogo base de cuentas para toda la operacion contable.",
        "Configuracion y control contable.",
        "Definir la estructura contable que usaran todos los demas modulos para generar asientos.",
        "Usalo en implementacion inicial, ajustes del catalogo o cuando aparezca una nueva operacion de negocio.",
        ["Criterio contable sobre activos, pasivos, patrimonio, ingresos, costos y gastos."],
        ["Cuentas utilizables por comprobantes, ventas, bancos, compras, nomina y reportes"],
        ["Codigo", "naturaleza", "clasificacion", "jerarquia y cuentas mal duplicadas"],
        ["comprobantes-integrados", "diario", "mayor", "balance-comprobacion"],
      ),
      module(
        "Comprobantes",
        "comprobantes-integrados",
        "basic",
        "Registro formal de comprobantes y asientos vinculados.",
        "Operaciones manuales y ajustes.",
        "Registrar hechos economicos que no nacen automaticamente desde otros modulos y dejar rastro auditable.",
        "Usalo para ingresos, egresos, traspasos, reclasificaciones y ajustes de cierre.",
        ["Fecha", "glosa", "detalle debe/haber", "cuentas correctas y referencia soporte"],
        ["Comprobante persistido", "asiento contable", "rastro de autorizacion o anulacion"],
        ["Equilibrio debe/haber", "estado del comprobante", "referencia documental y usuario responsable"],
        ["plan-cuentas", "diario", "mayor", "balance-comprobacion"],
      ),
      module(
        "Diario",
        "diario",
        "basic",
        "Bitacora cronologica de asientos y movimientos.",
        "Revision contable diaria.",
        "Revisar la historia completa de asientos generados por todos los procesos del sistema.",
        "Abrelo al revisar movimientos del dia, validar ajustes o rastrear el origen de un saldo.",
        ["Asientos ya generados desde modulos operativos o comprobantes manuales."],
        ["Vision cronologica de la contabilidad", "rastreo del origen por referencia"],
        ["Borradores", "duplicidades", "reversiones", "glosas incompletas"],
        ["comprobantes-integrados", "mayor", "balance-comprobacion"],
      ),
      module(
        "Mayor",
        "mayor",
        "basic",
        "Consulta de movimientos y saldos por cuenta.",
        "Analisis y conciliacion.",
        "Ver como se mueve cada cuenta a lo largo del tiempo y explicar su saldo final.",
        "Usalo cuando necesites analizar una cuenta puntual o justificar una variacion en balances.",
        ["Cuenta contable", "rango de fechas", "movimientos ya registrados."],
        ["Extracto por cuenta", "saldo inicial y final", "detalle por asiento origen"],
        ["Saldos anomalos", "movimientos sin soporte", "cuentas con comportamiento no esperado"],
        ["diario", "balance-comprobacion", "bancos", "conciliacion-bancaria"],
      ),
      module(
        "Balance Comprobacion",
        "balance-comprobacion",
        "basic",
        "Control de cuadre y consistencia contable.",
        "Pre-cierre y auditoria.",
        "Verificar que la contabilidad este equilibrada antes de emitir estados financieros o cierres.",
        "Usalo antes de reportes financieros, cierres mensuales o auditorias internas.",
        ["Asientos registrados del periodo."],
        ["Saldos deudores y acreedores", "base para revision de cuentas"],
        ["Cuadre total", "cuentas sin movimiento", "saldos invertidos", "clasificaciones incorrectas"],
        ["diario", "mayor", "balance-general", "estado-resultados"],
      ),
      module(
        "Balance General",
        "balance-general",
        "pro",
        "Situacion financiera de activos, pasivos y patrimonio.",
        "Gerencia y cierre financiero.",
        "Presentar una foto financiera ordenada de la empresa al cierre de un periodo.",
        "Usalo para cierre mensual, presentacion gerencial, credito bancario o revision de solvencia.",
        ["Contabilidad cerrada o al menos revisada del periodo."],
        ["Estado de situacion financiera", "lectura patrimonial", "base para decisiones gerenciales"],
        ["Inventario contable", "saldos bancarios conciliados", "cuentas por cobrar y pagar coherentes"],
        ["balance-comprobacion", "estado-resultados", "conciliacion-bancaria", "inventario"],
      ),
      module(
        "Resultados",
        "estado-resultados",
        "pro",
        "Ingresos, costos y utilidad del periodo.",
        "Rentabilidad y analisis gerencial.",
        "Medir el desempeno economico del negocio y entender de donde proviene la utilidad o la perdida.",
        "Usalo en cierres mensuales, analisis de rentabilidad y seguimiento gerencial.",
        ["Ingresos, costos y gastos correctamente registrados."],
        ["Resultado del periodo", "margenes", "lectura de desempeno"],
        ["Ventas anuladas", "costos incompletos", "gastos extraordinarios", "margenes fuera de tendencia"],
        ["facturacion", "compras", "balance-general", "analisis-financiero", "rentabilidad"],
      ),
    ],
  },
  {
    group: "Operaciones",
    description: "Procesos comerciales y administrativos del dia a dia.",
    modules: [
      module(
        "Facturacion",
        "facturacion",
        "basic",
        "Emision de facturas y control del ciclo comercial.",
        "Ventas y administracion.",
        "Registrar ventas, emitir comprobantes de salida y dejar impacto contable y tributario.",
        "Usalo para ventas formales con factura, seguimiento de documentos emitidos y control comercial.",
        ["Cliente", "productos o servicios", "precios", "condicion de pago", "datos fiscales"],
        ["Factura", "asiento de venta", "movimiento de stock si aplica", "base para cobranza"],
        ["Datos fiscales del cliente", "stock disponible", "estado de la factura", "anulacion o notas posteriores"],
        ["clientes", "productos", "credit-sales", "facturacion-electronica", "cuentas-cobrar-pagar"],
      ),
      module(
        "Punto de Venta",
        "punto-venta",
        "pro",
        "Venta rapida con ticket, cliente y cobro.",
        "Caja y retail.",
        "Agilizar ventas de mostrador o caja con un flujo comercial corto y operativo.",
        "Usalo en ventas rapidas, cobros inmediatos y atencion de mostrador.",
        ["Productos", "precios", "stock", "medios de pago", "cliente opcional"],
        ["Venta al contado", "ticket", "factura si corresponde", "baja de stock"],
        ["Caja diaria", "medios de pago", "productos sin stock", "cliente fiscal cuando se factura"],
        ["productos", "facturacion", "bancos", "cuentas-cobrar-pagar"],
      ),
      module(
        "Ventas Credito",
        "credit-sales",
        "pro",
        "Control de cartera, saldos y cobranzas.",
        "Empresas que venden a plazo.",
        "Gestionar ventas con plazo de cobro, seguimiento de saldo y cobranzas parciales.",
        "Usalo cuando la empresa no cobra todo al contado y necesita controlar vencimientos.",
        ["Cliente", "factura", "condicion de pago", "fechas de vencimiento"],
        ["Cartera por cobrar", "historial de cobros", "estado pendiente o pagado"],
        ["Vencimientos", "mora", "anticipos aplicados", "saldo pendiente"],
        ["facturacion", "clientes", "cuentas-cobrar-pagar", "flujo-caja"],
      ),
      module(
        "Notas C/D",
        "notas-credito-debito",
        "pro",
        "Ajustes comerciales y tributarios sobre operaciones emitidas.",
        "Devoluciones y correcciones.",
        "Corregir o complementar documentos comerciales ya emitidos sin perder trazabilidad.",
        "Usalo en devoluciones, descuentos posteriores, cargos adicionales o rectificaciones.",
        ["Documento origen", "motivo", "importes a ajustar", "validacion tributaria"],
        ["Nota de credito o debito", "impacto sobre saldo y contabilidad"],
        ["Documento base correcto", "motivo claro", "efecto en IVA, stock y cartera"],
        ["facturacion", "inventario", "cuentas-cobrar-pagar", "facturacion-electronica"],
      ),
      module(
        "Compras",
        "compras",
        "pro",
        "Registro de compras, credito fiscal y obligaciones.",
        "Abastecimiento y contabilidad.",
        "Registrar adquisiciones con efecto en inventario, gasto, activo y cuentas por pagar.",
        "Usalo al recibir facturas de proveedores o al documentar adquisiciones del negocio.",
        ["Proveedor", "documento", "items", "montos", "clasificacion contable"],
        ["Compra persistida", "credito fiscal", "cuenta por pagar", "ingreso a inventario si aplica"],
        ["NIT del proveedor", "clasificacion correcta", "impuestos", "fecha y soporte"],
        ["proveedores", "inventario", "libro-compras-ventas", "cuentas-cobrar-pagar"],
      ),
      module(
        "Proveedores",
        "proveedores",
        "pro",
        "Directorio y analisis de terceros proveedores.",
        "Compras y cuentas por pagar.",
        "Mantener limpia la base de terceros de compra y revisar el comportamiento de abastecimiento.",
        "Usalo al dar de alta proveedores, revisar historial de compras o controlar saldos.",
        ["Datos fiscales y comerciales del proveedor."],
        ["Maestro de proveedores", "base para compras y pagos"],
        ["NIT correcto", "contactos", "historial", "saldos pendientes"],
        ["compras", "cuentas-cobrar-pagar", "retenciones"],
      ),
      module(
        "Clientes",
        "clientes",
        "basic",
        "Base comercial con historial y datos fiscales.",
        "Ventas y cobranza.",
        "Organizar la cartera de clientes y asegurar que la facturacion salga con datos limpios.",
        "Usalo para altas comerciales, revision de historial y control de cobranza.",
        ["Nombre o razon social", "identificacion fiscal", "contacto y condiciones comerciales"],
        ["Maestro de clientes", "base para facturas y ventas a credito"],
        ["NIT/CI", "razon social", "clientes duplicados", "condicion de pago"],
        ["facturacion", "credit-sales", "cuentas-cobrar-pagar"],
      ),
    ],
  },
  {
    group: "Inventario y Activos",
    description: "Control fisico, valorizacion y patrimonio productivo.",
    modules: [
      module(
        "Productos",
        "productos",
        "basic",
        "Catalogo de productos y servicios con imagen principal.",
        "Ventas, POS e inventario.",
        "Centralizar la ficha maestra de lo que la empresa vende, compra o controla en almacen.",
        "Usalo cuando crees nuevos items, ajustes precios, cambies costos o cargues imagenes.",
        ["Codigo", "nombre", "categoria", "costo", "precio", "imagen opcional", "stock inicial si aplica"],
        ["Producto usable en ventas, POS, inventario y reportes"],
        ["Codigo unico", "precio/costo", "stock minimo", "imagen correcta", "tipo producto o servicio"],
        ["inventario", "facturacion", "punto-venta", "kardex"],
      ),
      module(
        "Inventario",
        "inventario",
        "basic",
        "Control de stock, valorizacion y alertas.",
        "Almacen y control interno.",
        "Supervisar existencias, movimientos y diferencias entre operacion fisica y contable.",
        "Usalo para revisar stock bajo, valorizacion, entradas y salidas.",
        ["Productos configurados", "movimientos de ventas, compras o ajustes."],
        ["Existencias", "alertas", "valuacion", "base para control operativo"],
        ["Stock bajo", "diferencias fisico/contable", "productos sin movimiento", "costos desactualizados"],
        ["productos", "compras", "facturacion", "kardex"],
      ),
      module(
        "Kardex",
        "kardex",
        "pro",
        "Historial detallado de movimientos por producto.",
        "Auditoria de inventario.",
        "Explicar cada entrada y salida de un producto con referencia documental.",
        "Usalo cuando un producto no cuadra o necesites rastrear una diferencia.",
        ["Producto y periodo a analizar."],
        ["Secuencia de movimientos", "saldo final por item", "rastro documental"],
        ["Movimientos sin referencia", "saltos de stock", "costos mal aplicados"],
        ["inventario", "compras", "facturacion", "punto-venta"],
      ),
      module(
        "Activos Fijos",
        "activos-fijos",
        "pro",
        "Control de bienes, depreciacion y valor en libros.",
        "Patrimonio y cierre anual.",
        "Gestionar activos de largo plazo, su depreciacion y su impacto contable.",
        "Usalo en altas de bienes, depreciaciones, bajas y revision patrimonial.",
        ["Datos del activo", "fecha de alta", "costo", "vida util", "valor residual"],
        ["Ficha del activo", "depreciacion", "base patrimonial"],
        ["Vida util", "depreciacion acumulada", "bajas no registradas", "cuentas contables asociadas"],
        ["compras", "balance-general", "estado-resultados"],
      ),
    ],
  },
  {
    group: "Finanzas",
    description: "Tesoreria, liquidez y conciliacion financiera.",
    modules: [
      module(
        "Bancos",
        "bancos",
        "pro",
        "Mesa de tesoreria con cuentas y movimientos.",
        "Tesoreria diaria.",
        "Centralizar cuentas bancarias, registrar movimientos y preparar la conciliacion.",
        "Usalo para registrar cuentas, movimientos manuales o importados y revisar saldos.",
        ["Cuenta bancaria", "movimientos", "relacion contable de la cuenta"],
        ["Saldo por cuenta", "movimientos bancarios", "base para conciliacion y flujo"],
        ["Movimientos duplicados", "tipo de movimiento", "saldo", "origen importado o manual"],
        ["conciliacion-bancaria", "flujo-caja", "mayor"],
      ),
      module(
        "Conciliacion",
        "conciliacion-bancaria",
        "pro",
        "Conciliacion auditable de banco versus libros.",
        "Cierre mensual bancario.",
        "Comparar extractos bancarios contra asientos reales para explicar diferencias.",
        "Usalo al cierre mensual o cuando un saldo bancario no coincide con libros.",
        ["Cuenta bancaria", "fecha de corte", "movimientos importados", "asientos contables"],
        ["Partidas conciliadas", "excepciones", "ajustes propuestos", "estado de conciliacion"],
        ["Diferencia final", "partidas en transito", "cargos bancarios no registrados", "ajustes pendientes"],
        ["bancos", "diario", "mayor", "flujo-caja"],
      ),
      module(
        "Flujo Caja",
        "flujo-caja",
        "pro",
        "Lectura y proyeccion de liquidez.",
        "Gerencia financiera.",
        "Anticipar entradas y salidas de dinero para tomar decisiones de caja.",
        "Usalo en seguimiento semanal, negociacion de pagos o prevision de faltantes.",
        ["Bancos", "cuentas por cobrar", "cuentas por pagar", "movimientos planificados"],
        ["Proyeccion de liquidez", "horizonte de cobros y pagos", "escenarios de caja"],
        ["Concentracion de vencimientos", "baches de liquidez", "dependencia de pocos cobradores"],
        ["bancos", "credit-sales", "cuentas-cobrar-pagar", "compras"],
      ),
      module(
        "CxC / CxP",
        "cuentas-cobrar-pagar",
        "pro",
        "Consolidado de cartera y obligaciones.",
        "Cobranza y pagos.",
        "Ver en una sola vista quien debe a la empresa y a quien debe la empresa.",
        "Usalo en comites de cobranza, programacion de pagos y control de vencimientos.",
        ["Facturas", "pagos", "compras", "anticipos", "proveedores y clientes"],
        ["Cartera consolidada", "ranking de vencidos", "historial de cobros y pagos"],
        ["Saldos vencidos", "documentos sin aplicar", "anticipos no compensados"],
        ["credit-sales", "compras", "bancos", "flujo-caja"],
      ),
    ],
  },
  {
    group: "Impuestos SIN",
    description: "Control fiscal, cumplimiento y circuito de revision tributaria.",
    modules: [
      module(
        "Libro C/V",
        "libro-compras-ventas",
        "pro",
        "Libro fiscal SIAT con control de exportacion.",
        "Cierre tributario mensual.",
        "Preparar el libro de compras y ventas a partir de operaciones reales y separar incidencias antes de exportar.",
        "Usalo antes de presentar IVA o al revisar la consistencia del periodo fiscal.",
        ["Facturas, compras, estados SIN y periodo fiscal."],
        ["Libro filtrado", "base exportable", "alertas de ventas observadas"],
        ["Facturas observadas", "compras sin soporte", "ventas pendientes de validacion SIN"],
        ["facturacion", "facturacion-electronica", "declaraciones-tributarias"],
      ),
      module(
        "Declaraciones",
        "declaraciones-tributarias",
        "pro",
        "Calendario fiscal y registro de declaraciones.",
        "IVA, IT e IUE.",
        "Controlar vencimientos, registrar declaraciones y advertir incidencias del periodo.",
        "Usalo para preparar, revisar y marcar como presentadas las obligaciones tributarias.",
        ["Tipo de obligacion", "periodo", "monto declarado", "configuracion fiscal"],
        ["Registro de declaracion", "estado presentada/pendiente", "alertas de revision previa"],
        ["Periodo correcto", "duplicados", "montos negativos", "facturas electronicas rechazadas del mismo periodo"],
        ["libro-compras-ventas", "facturacion-electronica", "cumplimiento-normativo"],
      ),
      module(
        "Cumplimiento",
        "cumplimiento-normativo",
        "pro",
        "Seguimiento normativo y regulatorio.",
        "Responsable tributario.",
        "Concentrar obligaciones, vencimientos, alertas y estado de cumplimiento del negocio.",
        "Usalo para revisar lo que esta por vencer o quedo observado en materia fiscal y regulatoria.",
        ["Declaraciones", "retenciones", "nomina", "configuracion tributaria", "facturas observadas"],
        ["Alertas ejecutivas", "cola de cumplimiento", "riesgos priorizados"],
        ["Obligaciones vencidas", "facturas SIN rechazadas", "planillas o retenciones pendientes"],
        ["declaraciones-tributarias", "facturacion-electronica", "retenciones", "nomina"],
      ),
      module(
        "Retenciones",
        "retenciones",
        "pro",
        "Emision y control de retenciones fiscales.",
        "RC-IVA y obligaciones relacionadas.",
        "Registrar retenciones, su estado y su soporte contable y documental.",
        "Usalo cuando la empresa deba emitir o controlar certificados de retencion.",
        ["Tercero", "tipo de retencion", "base imponible", "monto", "fecha"],
        ["Retencion emitida", "estado presentada/anulada", "asiento contable si aplica"],
        ["Tipo correcto", "calculo del monto", "estado de presentacion", "soporte vinculado"],
        ["compras", "cumplimiento-normativo", "nomina"],
      ),
      module(
        "Fact. Electronica",
        "facturacion-electronica",
        "pro",
        "Control de CUF, CUFD y recepcion SIN asistida.",
        "Incidencias electronicas y revision fiscal.",
        "Supervisar el estado electronico de las facturas y resolver rechazos, pendientes o datos incompletos.",
        "Usalo al revisar el periodo fiscal o cuando una factura tenga observaciones del flujo SIN.",
        ["Factura emitida", "datos fiscales", "configuracion SIN", "actividad economica y punto de venta"],
        ["Estado SIN", "soportes", "cola de incidencias", "reenvio o correccion asistida"],
        ["NIT invalido", "CUF/CUFD faltante", "configuracion incompleta", "facturas rechazadas o pendientes"],
        ["facturacion", "libro-compras-ventas", "declaraciones-tributarias", "cumplimiento-normativo"],
      ),
    ],
  },
  {
    group: "Planificacion",
    description: "Presupuesto, control de ejecucion y lectura por areas.",
    modules: [
      module(
        "Presupuestos",
        "presupuestos",
        "pro",
        "Planificacion y control presupuestario.",
        "Gerencia y control financiero.",
        "Comparar lo planificado contra lo realmente ejecutado y detectar desviaciones.",
        "Usalo en planeacion mensual, trimestral o anual y en seguimiento gerencial.",
        ["Periodo", "lineas presupuestarias", "montos meta"],
        ["Presupuesto por periodo", "desvios", "seguimiento de ejecucion"],
        ["Desviaciones significativas", "rubros sobreejecutados", "presupuestos desactualizados"],
        ["centros-costo", "estado-resultados", "reportes"],
      ),
      module(
        "Centros Costo",
        "centros-costo",
        "pro",
        "Seguimiento de ejecucion por area o unidad.",
        "Costos y control gerencial.",
        "Entender que area consume recursos, como ejecuta su presupuesto y que rentabilidad genera.",
        "Usalo cuando la empresa gestiona gastos o ingresos por unidad, sucursal o departamento.",
        ["Centro definido", "presupuesto", "cuentas contables asociadas", "responsable"],
        ["Ejecucion por centro", "desvios", "lectura por area"],
        ["Cuentas mal asociadas", "presupuesto agotado", "responsable no asignado"],
        ["presupuestos", "estado-resultados", "rentabilidad"],
      ),
    ],
  },
  {
    group: "Recursos Humanos",
    description: "Operacion laboral, planillas y control del personal.",
    modules: [
      module(
        "Nomina",
        "nomina",
        "pro",
        "Planillas, RC-IVA y pago de personal.",
        "RRHH y contabilidad laboral.",
        "Generar planillas salariales, controlar RC-IVA y registrar el pago con impacto contable.",
        "Usalo en cada cierre de mes laboral o al procesar nuevas planillas.",
        ["Empleados", "conceptos salariales", "periodo", "facturas RC-IVA si aplica"],
        ["Planilla persistida", "detalle por empleado", "asiento de pago", "estado del periodo"],
        ["Periodo correcto", "netos", "RC-IVA", "planillas duplicadas", "estado de pago"],
        ["empleados", "cumplimiento-normativo", "diario"],
      ),
      module(
        "Empleados",
        "empleados",
        "pro",
        "Directorio y estado del personal.",
        "Administracion de personal.",
        "Mantener la base laboral actualizada para que nomina y control interno operen correctamente.",
        "Usalo para altas, bajas, actualizaciones y revision del padron laboral.",
        ["Datos personales", "cargo", "estado", "condicion laboral"],
        ["Padron de empleados", "base para nomina y control organizacional"],
        ["Datos incompletos", "duplicados", "empleados inactivos aun en nomina"],
        ["nomina"],
      ),
    ],
  },
  {
    group: "Reportes",
    description: "Informacion ejecutiva, analitica y de control.",
    modules: [
      module(
        "Reportes",
        "reportes",
        "pro",
        "Centro de reportes operativos y financieros.",
        "Gerencia y control.",
        "Emitir reportes consolidados para toma de decisiones o respaldo documental.",
        "Usalo cuando necesites exportar informacion o armar cortes gerenciales.",
        ["Datos del periodo", "filtros adecuados", "modulos alimentados correctamente"],
        ["Reportes descargables", "visiones ejecutivas", "resumenes operativos"],
        ["Filtros correctos", "coherencia del periodo", "base de datos actualizada"],
        ["dashboard", "balance-general", "estado-resultados", "analisis-financiero"],
      ),
      module(
        "Analisis",
        "analisis-financiero",
        "pro",
        "Ratios y lectura financiera ejecutiva.",
        "Direccion y analisis.",
        "Traducir la contabilidad a indicadores de liquidez, rentabilidad y desempeno.",
        "Usalo en comites gerenciales, presentaciones o revisiones de estrategia.",
        ["Estados financieros y datos operativos consistentes."],
        ["Indicadores", "tendencias", "insumos para decision"],
        ["Comparabilidad entre periodos", "datos base consistentes", "lecturas fuera de contexto"],
        ["balance-general", "estado-resultados", "reportes"],
      ),
      module(
        "IA",
        "analisis-inteligente",
        "enterprise",
        "Lectura analitica avanzada del sistema.",
        "Hallazgos y soporte ejecutivo.",
        "Detectar hallazgos, patrones y senales de riesgo sobre datos ya persistidos.",
        "Usalo cuando necesites una lectura rapida de riesgos, tendencias o anomalias.",
        ["Datos suficientemente completos en contabilidad, ventas, impuestos y finanzas."],
        ["Sugerencias de revision", "hallazgos", "alertas interpretativas"],
        ["Calidad del dato base", "suposiciones del analisis", "validacion humana del hallazgo"],
        ["analisis-financiero", "auditoria-avanzada", "dashboard"],
      ),
      module(
        "Rentabilidad",
        "rentabilidad",
        "enterprise",
        "Margen y analisis de rentabilidad.",
        "Comercial y costos.",
        "Entender que productos, lineas o unidades aportan mas resultado.",
        "Usalo al revisar mix comercial, precios o eficiencia de costos.",
        ["Ventas", "costos", "centros de costo", "productos"],
        ["Margen por linea o categoria", "hallazgos de rentabilidad"],
        ["Costos incompletos", "productos sin costo real", "comparaciones sesgadas por periodo"],
        ["productos", "estado-resultados", "centros-costo"],
      ),
      module(
        "Auditoria",
        "auditoria-avanzada",
        "enterprise",
        "Hallazgos y control interno avanzado.",
        "Auditoria y cierre.",
        "Identificar excepciones, anomalias y riesgos que merecen revision prioritaria.",
        "Usalo en pre-cierre, auditoria interna o cuando sospeches fallas de control.",
        ["Datos transaccionales y contables persistidos."],
        ["Hallazgos priorizados", "riesgos por modulo", "base para accion correctiva"],
        ["Criticidad", "reincidencias", "modulo origen", "soporte del hallazgo"],
        ["diario", "analisis-inteligente", "cumplimiento-normativo"],
      ),
    ],
  },
  {
    group: "Configuracion",
    description: "Parametros maestros, continuidad y soporte de adopcion.",
    modules: [
      module(
        "Configuracion",
        "configuracion",
        "basic",
        "Parametros de empresa, fiscalidad y SIN.",
        "Implementacion y mantenimiento.",
        "Definir la identidad fiscal y operativa de la empresa para que el resto del sistema funcione bien.",
        "Usalo al comenzar y cuando cambien parametros fiscales, puntos de venta o datos corporativos.",
        ["Datos legales y fiscales de la empresa", "credenciales o parametros SIN"],
        ["Configuracion base usable por facturacion, declaraciones y demas modulos"],
        ["NIT valido", "actividad economica", "codigo de sistema", "punto de venta y sucursal"],
        ["dashboard", "facturacion-electronica", "declaraciones-tributarias"],
      ),
      module(
        "Backup",
        "backup",
        "pro",
        "Respaldo operativo y continuidad.",
        "Administrador del sistema.",
        "Dar visibilidad a la continuidad operativa y respaldo de informacion.",
        "Usalo para control periodico de copias o seguimiento de politicas de respaldo.",
        ["Politica interna de respaldo y revision operativa."],
        ["Registro de respaldo o estado de continuidad"],
        ["Ultima ejecucion", "frecuencia", "responsable", "evidencia de respaldo"],
        ["admin-dashboard", "admin-logs"],
      ),
      module(
        "Tutorial",
        "tutorial",
        "basic",
        "Centro de ayuda, onboarding y capacitacion.",
        "Nuevos usuarios y reciclaje.",
        "Explicar que hace cada modulo, como se conectan entre si y en que orden conviene operar.",
        "Usalo al implementar, capacitar equipos nuevos o resolver dudas de proceso.",
        ["Acceso al sistema y necesidad de capacitacion."],
        ["Rutas operativas", "guia maestra", "manual ampliado"],
        ["Que el contenido refleje el sistema real y no material ficticio"],
        ["dashboard", "configuracion"],
      ),
    ],
  },
  {
    group: "Administracion",
    description: "Backoffice del producto, soporte y trazabilidad global.",
    modules: [
      module(
        "Panel Admin",
        "admin-dashboard",
        "admin",
        "Control global de la capa administrativa.",
        "Administrador de plataforma.",
        "Monitorear la salud general del producto, usuarios y operacion administrativa.",
        "Usalo al revisar soporte, actividad global o metricas administrativas.",
        ["Acceso de administrador."],
        ["KPIs administrativos", "vision general de operacion interna"],
        ["Actividad anomala", "planes vencidos", "usuarios bloqueados"],
        ["admin-users", "admin-subscriptions", "admin-logs"],
      ),
      module(
        "Gestion Usuarios",
        "admin-users",
        "admin",
        "Administracion avanzada de usuarios.",
        "Soporte y seguridad.",
        "Gestionar acceso, estado y consistencia de usuarios de la plataforma.",
        "Usalo al dar altas, revocar permisos o investigar problemas de acceso.",
        ["Datos del usuario y permisos requeridos."],
        ["Usuario habilitado, bloqueado o corregido"],
        ["Roles correctos", "duplicados", "estado de acceso"],
        ["admin-dashboard", "admin-logs"],
      ),
      module(
        "Suscripciones",
        "admin-subscriptions",
        "admin",
        "Planes y estados comerciales del SaaS.",
        "Backoffice comercial.",
        "Controlar que plan tiene cada cuenta y su estado comercial.",
        "Usalo en soporte comercial, renovaciones o revision de acceso por plan.",
        ["Cliente o cuenta", "estado comercial", "plan"],
        ["Actualizacion de suscripcion", "visibilidad comercial"],
        ["Vigencias", "bloqueos por plan", "inconsistencias de facturacion"],
        ["admin-dashboard", "admin-payments"],
      ),
      module(
        "Pagos Bolivia",
        "admin-payments",
        "admin",
        "Seguimiento administrativo de pagos locales.",
        "Soporte comercial.",
        "Revisar el estado administrativo de pagos y conciliaciones comerciales locales.",
        "Usalo cuando soporte o backoffice necesiten confirmar pagos de clientes.",
        ["Registros de pago y referencia comercial."],
        ["Seguimiento de pagos", "estado administrativo"],
        ["Pagos sin aplicar", "referencias incompletas", "desfase con suscripcion"],
        ["admin-subscriptions", "admin-logs"],
      ),
      module(
        "Logs Actividad",
        "admin-logs",
        "admin",
        "Trazabilidad de actividad y eventos.",
        "Auditoria y soporte.",
        "Rastrear quien hizo que y cuando, para soporte, control y auditoria.",
        "Usalo al investigar incidentes, cambios criticos o actividad sospechosa.",
        ["Eventos registrados por la plataforma."],
        ["Historial trazable por usuario y accion"],
        ["Eventos criticos", "patrones anomalos", "acciones sensibles sin contexto"],
        ["admin-dashboard", "admin-users"],
      ),
    ],
  },
];
